language: python
python:
- '3.5'
env:
- TRAVIS=1
install:
- python setup.py install
script:
- python setup.py test --addopts -v
before_install:
- sudo apt-get update -qq
- sudo apt-get install -qq libatlas-dev libatlas-base-dev liblapack-dev gfortran
